# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010iclg225-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/BME/MSC1/RA/HF/axi_spi/axi_spi.cache/wt [current_project]
set_property parent.project_path D:/BME/MSC1/RA/HF/axi_spi/axi_spi.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/BME/MSC1/RA/HF/axi_spi/axi_spi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/BME/MSC1/RA/HF/axi_spi/axi_spi.srcs/sources_1/imports/SRC/axi.vhd
  D:/BME/MSC1/RA/HF/axi_spi/axi_spi.srcs/sources_1/imports/SRC/spi_pkg.vhd
  D:/BME/MSC1/RA/HF/axi_spi/axi_spi.srcs/sources_1/imports/SRC/spi_if.vhd
  D:/BME/MSC1/RA/HF/axi_spi/axi_spi.srcs/sources_1/imports/SRC/timer.vhd
  D:/BME/MSC1/RA/HF/axi_spi/axi_spi.srcs/sources_1/imports/SRC/spi_top.vhd
  D:/BME/MSC1/RA/HF/axi_spi/axi_spi.srcs/sources_1/imports/SRC/axi_spi_top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top axi_spi_top -part xc7z010iclg225-1L


write_checkpoint -force -noxdef axi_spi_top.dcp

catch { report_utilization -file axi_spi_top_utilization_synth.rpt -pb axi_spi_top_utilization_synth.pb }
